version: '3.9'

services:
  mainstream_v1:
    container_name: mainstream_v1
    build:
      context: .
      dockerfile: Dockerfile
    image: mainstream_v1:latest
    ports:
      - "8566:8501"
    volumes:
      - .:/app
      - ./.secretcontainer:/app/.secretcontainer
    restart: unless-stopped
    pull_policy: never   
